version: '3.8'

services:
  nginx-container:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-container  # Proper string value
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - internal
    volumes:
      - ./nginx/2127_little_fashion:/usr/share/nginx/html:ro

  firefox-container:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox-container  # Proper string value
    ports:
      - "${FIREFOX_PORT}:3000"
    networks:
      - internal
    environment:
      PUID: "1000"  # Proper YAML format
      PGID: "1000"
      TZ: "Etc/UTC"
      FF_OPEN_URL: "http://nginx-container"
    volumes:
      - ./firefox-config:/config
    shm_size: "1gb"
    restart: unless-stopped
    depends_on:
      - nginx-container

networks:
  internal:
    driver: bridge
