services:
  nginx-container:
    build: ./nginx
    container_name: nginx-container
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - internal
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro

  firefox-container:
    build: ./firefox
    container_name: firefox-container
    ports:
      - "${FIREFOX_PORT}:5400"
    networks:
      - internal
    environment:
      - DISPLAY=:0

networks:
  internal:
    driver: bridge

