version: '3.8'

services:
  nginx-container:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-container
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - internal
    volumes:
      - ./nginx/2127_little_fashion:/usr/share/nginx/html:ro

  firefox-container:
    image: lscr.io/linuxserver/firefox:latest
    container_name:
    ports:
      - "${FIREFOX_PORT}:3000"
    networks:
      - internal
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - firefox-profile:/config:rw  
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - FF_OPEN_URL=http://nginx-container
    restart: unless-stopped  
    shm_size: "2gb"  
    depends_on:
      - nginx-container

networks:
  internal:
    driver: bridge

volumes:
  firefox-profile:
