version: '3.8'  
services:
  nginx-container:
    context: .
    dockerfile: ./nginx/Dockerfile
    container_name: nginx-container
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - internal
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro

  firefox-container:
    image: jlesage/firefox
    container_name: firefox-container
    ports:
      - "${FIREFOX_PORT}:5800"
    networks:
      - internal
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 
    environment:
      - DISPLAY=${DISPLAY:-:0}
    depends_on:
      - nginx-container

networks:
  internal:
    driver: bridge
